openshift/assisted-installer-agent

- README.md
- src/commands/register_node.go
- src/commands/step_processor.go
- src/config/agent_config.go
- src/session/inventory_session.go
This PR adds control over the default HTTPS transport by adding `--insecure` option (skip certificate validation) and `--cacert` option (provide a custom root CA certificate as a PEM file).
> MGMT-1695 Support HTTPS transport

- go.sum
- src/config/agent_config.go
- subsystem/docker-compose.yml
Remove `--host` and `--port`.
Run `go mod tidy` to clean up unused dependencies.
> MGMT-1713 Remove deprecated host and port parameters

- Dockerfile.assisted_installer_agent
- Makefile
- go.mod
- go.sum
- src/apivip_check/apivip_check.go
- src/apivip_check/apivip_check_test.go
- src/apivip_check/main/main.go
- src/apivip_check/utils.go
- subsystem/apivip_check_test.go
* Added apivip_check command:
- For ensuring connectivity between the node to and the API.
- Done by invoking a GET request to <api>/config/worker (to download the worker.ign file).
* Added relevant tests with wiremock stubs in subsystem/apivip_check_test.
> MGMT-2075 API VIP connectivity check command

- go.mod
- go.sum
- src/apivip_check/apivip_check.go
- src/apivip_check/apivip_check_test.go
- subsystem/apivip_check_test.go
Added network CIDR verification to API VIP connectivity check:
- Parse IP from API VIP.
- Get interfaces of the node.
- Calculate CIDRs by interfaces.
- API is verified if contained in one of the CIDRs.
> MGMT-2318 added network CIDR verification to API VIP check

- src/commands/step_processor.go
Adding log for better debug abilities.
`Oct 13 11:29:24 test-infra-cluster-assisted-installer-master-1 agent[1782]: time="13-10-2020 11:29:24" level=info msg="Executing step: <dhcp-lease-allocate-65af5fd9>, command: <podman>, args: <[run --privileged --net=host --rm --quiet -v /var/log:/var/log -v /run/systemd/journal/socket:/run/systemd/journal/socket quay.io/ocpmetal/assisted-installer-agent:latest dhcp_lease_allocate {\"api_vip_mac\":\"00:1a:4a:94:cc:16\",\"ingress_vip_mac\":\"00:1a:4a:b8:f7:25\",\"interface\":\"ens3\"}]>" file="step_processor.go:67" request_id=747ae4db-1f73-4014-83b6-cca6ef2e3bd0`
`Oct 13 11:29:24 test-infra-cluster-assisted-installer-master-1 agent[1782]: time="13-10-2020 11:29:24" level=info msg="Executing step: <install-6325892d>, command: <bash>, args: <[-c podman …
> OCPBUGSM-19005 add log with StepId

- Dockerfile.assisted_installer_agent-build
- go.mod
- go.sum
- src/config/logs_sender_config.go
- src/logs_sender/mock_LogsSender.go
- src/logs_sender/send_logs.go
- src/logs_sender/send_logs_test.go
We will now also send to `assisted-service` `installer-gather.sh` logs
on cluster installation cancel of error.
In case the installation succeed, those logs won't be sent, it is
parametrized and can be changed.
> MGMT-2431: Adding 'installer-gather.sh' to logs_sender on failure.

- src/commands/step_processor.go
```
> exit-code <255>Sending step <free-addresses> reply output <[{"free_addresses...> error <> exit-code <0>Sending step <free-addresses> reply output <> error <nmap: Target.cc:503: void Target::stopTimeOutClock(const timeval*): Assertion `htn.toclock_running == true' failed.
```
> MGMT-2347: trim the free-addresses message

- src/logs_sender/send_logs.go
`oc` command is used in `installer-gather.sh` and it need to have access
to Openshift API server.
> NO-ISSUE: Configuring privilege command to run using host network namespace.

- Dockerfile.assisted_installer_agent
- src/inventory/bmc.go
- src/inventory/bmc_test.go
- Loading kernel modules in a container is meaningless and produces errors in logs - so it was removed
/cc @ronniel1 
/cc @tsorya
> MGMT-2440 Fix the errors in inventory when trying to get BMC information

- Dockerfile.assisted_installer_agent
- go.mod
- go.sum
- src/inventory/dependencies.go
- src/inventory/mock_IDependencies.go
- src/inventory/system_vendor.go
- src/inventory/system_vendor_test.go
Continuing https://github.com/openshift/assisted-service/pull/688
- Updated assisted-service to the latest version that includes the PR above
- Replaced lshw with simpler ghw (I saw lshw outputting invalid JSON on some platforms, and while it may be a problem with the lshw version on those platforms and not in the version we put in our container, out of fear that some hardware causes it to misbehave, I thought it was best to just replace it with something simpler like ghw which we already depend on and use in other places in this code)
- Populated new models.SystemVendor.Virtual field with true/false according to whether the ProductName field looks like a known VM technology
> MGMT-792 - Updated assisted-service, replaced lshw with ghw, populated is-vm field

- src/config/logs_sender_config.go
- src/logs_sender/mock_LogsSender.go
- src/logs_sender/send_logs.go
- src/logs_sender/send_logs_test.go
- src/util/execute.go
If not supplied, `installer-gather.sh` will try to get this information
using `oc get nodes` but the use case we are trying to get logs for is
the one in which part of the masters didn't join the cluster so `oc get
nods` won't work.
Masters host names are retrieved from `assisted-service` API.
Also added gatherID to the log-bundle created.
> MGMT-2678: Supplying masters host names to installer-gather.sh.

- src/config/logs_sender_config.go
- src/logs_sender/mock_LogsSender.go
- src/logs_sender/send_logs.go
- src/logs_sender/send_logs_test.go
- src/util/execute.go
If not supplied, `installer-gather.sh` will try to get this information
using `oc get nodes` but the use case we are trying to get logs for is
the one in which part of the masters didn't join the cluster so `oc get
nods` won't work.
Masters IPs are added to logs cmd on `assisted-service` side.
Also:
* Updated LogsSender.ExecPrivileged to reuse util.ExecPrivileged
* Added gatherID to the log-bundle created
* Broke the logs of `installer-gather.sh` to separate lines
> MGMT-2678: Supplying non-bootstrap masters IPs to installer-gather.sh (#90)

- Dockerfile.assisted_installer_agent
- go.mod
- go.sum
- src/inventory/disks.go
- src/inventory/disks_test.go
- Updated assisted service to latest version
- Using smartctl to populate the Smart field in inventory host disks
- Organized disks_test.go a bit
> MGMT-3033 - Populating S.M.A.R.T. field in inventory host disks

- src/logs_sender/send_logs.go
- src/logs_sender/send_logs_test.go
Moved installer-gather to run first so its own logs are included in the
gathered agent logs.
Before the change:
```
...
Nov 25 06:12:37 test-infra-cluster-assisted-installer-master-0 logs_sender[11609]: time="25-11-2020 06:12:37" level=info msg="Start gathering journalctl logs with tags [agent installer] and services [bootkube]" file="send_logs.go:146"
Nov 25 06:12:37 test-infra-cluster-assisted-installer-master-0 logs_sender[11609]: time="25-11-2020 06:12:37" level=info msg="Running journalctl with filters [TAG=agent]" file="send_logs.go:109"
```
After the change:
```
...
Nov 25 07:03:58 test-infra-cluster-assisted-installer-master-2 logs_sender[11660]: time="25-11-2020 07:03:58" level=info msg="Start gathering journalctl logs with tags [agent installer], services [bootkube] and …
```
> NO-ISSUE: Changing the order of logs gathering.

- Dockerfile.assisted_installer_agent
Since centos:8 is using an older version of `smartmontools` (`smartctl` needed for the inventory command), we download the fedora 32 RPM package for `smartmontools` and install it instead of using the centos repos. (We need version 7.1+ for the `--json=c` flag to work).
Note that doing this is NOT needed in the downstream Dockerfile, the base image used there is `openshift/ose-base:ubi8` and it has the 7.1 version of `smartmontools` in the repos
> MGMT-3033 - Use newer smartmontools from the Fedora 32 repositories in upstream Dockerfile

- go.mod
- go.sum
- src/inventory/dependencies.go
- src/inventory/interfaces.go
- src/inventory/interfaces_test.go
- src/inventory/mock_IDependencies.go
- src/inventory/routes.go
IPV6 addresses many times don't have the correct network prefix associated.  Instead,
a prefix values of 128 is attached.  Since we need this prefix to calculate host-networks
and Machine Network CIDR, this value needs to be fixed.
The change takes the correct network prefix from Route Advertisement records
and fixes them in the IPv6 addresses that are returned as part of the inventory.
> MGMT-2777 Adapt IPv6 network prefix by using RA routes

- src/commands/step_processor.go
We want step executoin failures to show up on the agent log and not just the service log.
> OCPBUGSM-19005 - Print step output after step execution fails

- src/logs_sender/mock_LogsSender.go
- src/logs_sender/send_logs.go
- src/logs_sender/send_logs_test.go
Added system-coredump file and dmesg output to logs collector
(should be added to each host logs tar in case of installation error).
> MGMT-2858 LogsSender: added coredump and dmesg

- Dockerfile.assisted_installer_agent
- src/commands/connectivity_check.go
- src/connectivity_check/main/main.go
- src/util/network.go
Use ndisc6 to check L2 connectivity between nodes and receive a remote's MAC address.
For now there is a limitation that the outgoing IP address cannot be detected.
> MGMT-3120 IPv6 connectivity check

- src/inventory/disks.go
- src/inventory/disks_test.go
Turns out [smartctl exit-codes are meaningful](https://linux.die.net/man/8/smartctl) (See "Return Values" section).
In the current implementation of the agent's smartctl invocation, it's assumed that non-zero exit code is smartctl itself failing, but turns out smartctl also communicates *disk* failures via its exit code as linked above.
What we did prior to this PR is simply discard all S.M.A.R.T. information when the exit-code is non-zero, which is the worst thing we could possibly do - because when the exit code indicates disk failure, that's when the SMART info is most interesting to relay to the service.
Proposed change:
EDIT: Simply ignore the exit code. Pass the output to the service. Let it decide on its own what to do with that information.
For the record, this is the parsing that …
> MGMT-3211 - Never ignore smartctl, regardless of exit code

- src/logs_sender/send_logs.go
Use ExecutePrivileged (i.e. nsenter1) for coredumpctl execution.
This is needed for getting the core dumps in host context,
otherwise, coredumpctl fails to get sd-bus ("Failed to acquire bus")
> MGMT-2858: coredumpctl - use priviliged

- src/ntp_synchronizer/ntp_synchronizer.go
- src/ntp_synchronizer/ntp_synchronizer_test.go
In case could not determine whether a new server is already configured -
just log.
In case adding a new server failed - just log as well.
We always want to receive the current NTP sources from the agent.
> OCPBUGSM-21434 NTP: Ignore adding server failures

- Dockerfile.assisted_installer_agent
- src/commands/connectivity_check.go
- src/commands/connectivity_check_test.go
- src/free_addresses/free_addresses.go
- src/util/nmap/types.go
Replace ndisc6 because it cannot handle concurrent discovery
> MGMT-3194 Use nmap for L2 connectivity check

- src/fio_perf_check/fio_perf_check.go
`Dec 31 14:03:10 test-infra-cluster-assisted-installer-master-0 fio_perf_check[4074]: time="31-12-2020 14:03:10" level=info msg="FIO result on disk /dev/vda :fdatasync duration 6 ms , threshold: 1000 ms" file="fio_perf_check.go:42"`
> MGMT-3026 Add log of FIO result

- Makefile
- subsystem/docker-compose.yml
Use quay.io images for subsystem images - dhcpd, wiremock
> Get test images from quay.io

- subsystem/docker-compose.yml
quay.io/cloudctl/dhcp:ubi tag was deleted. For now moving to latest tag
> Move cloudctl/dhcp:ubi to cloudctl/dhcp:latest

- Dockerfile.assisted_installer_agent
- Makefile
Updated Dockerfile to build without running `make build` first.
I tested the `skipper make build-image` and `skipper make subsystem` locally as well.
> MGMT-3315 Multi-stage agent Dockerfile

- Jenkinsfile
- Makefile
* Currently collects from the following containers:
- dhcp
- wiremock
* Collect agent journal (last hour).
The subsystem call to `_test` Makefile entery was added with a '`-`' prefix to ignore errors, as stated https://www2.ipp.mpg.de/~dpc/gmake/make_47.html
The reason that it would otherwise stop execution with a failed test and won't collect the logs, which we obviously want, especially in those cases.
> MGMT-4346 collect logs from containers in Jenkins Post

- src/commands/step_processor.go
Logging the step execution failure with Error instead of Info message will help in analyzing logs quickly for failures.
> NO-ISSUE: Use 'Errorf' instead of 'Infof' for step failure

- src/inventory/disks.go
- src/inventory/disks_test.go
Support special case where two disk shares the same busType. We prefer to pretend they have no bus path at all, to avoid confusing between them
(cherry picked from commit e217062c630886a821eefecaa3fc3ab62cc1a0b6)
> OCPBUGSM-27560 Duplicate installation disk. (#192)

- go.mod
- go.sum
- src/inventory/interfaces.go
- src/inventory/interfaces_test.go
all the ipv6 addresses starting with "fe80" are local link ones and
should be filtered out from the inventory result cause they are not
routable
> OCPBUGSM-27088 Filter out ipv6 local link addresses from inventory.

- src/commands/connectivity_check.go
- src/commands/connectivity_check_test.go
This PR extends the L3 connectivity information gathered by the agent by capturing the average latency (RTT) and the packet loss information per host connection.
Code has been refactored and unit tests extended to cover the new functionality as well as the aggregation process to validate the refactored code.
This [PR](https://github.com/openshift/assisted-service/pull/1432) is the counterpart in the assisted-service.
@pkliczewski @jakub-dzon @machacekondra @masayag @YuviGold please review at your discretion in the meanwhile.
/Jordi
> MGMT-4718 Capture network latency and packet loss at L3 network connectivity

- src/commands/reply_cache.go
- src/commands/step_processor.go
- Since some of the messages are cleared from host database row when agent disconnects, it is essential to invalidate the cache such case
- Since the cache is needed for optimization only, it will not harm the system functionality
/cc @tsorya
> MGMT-6668 Invalidate agent cache when there is a problem to perform get next steps from assisted service

- Jenkinsfile
Fixes a small bug where the wrong format date string was used.
I've been using the Jenkins replay functionality to test Jenkins changes:
Here is the manual replay log:
http://assisted-jenkins.usersys.redhat.com/job/assisted-service/job/ocm-2.3/36/console
First one is YMMdd (new), second is Ymd (current) third is H for the current hour.
Signed-off-by: Lisa Rashidi-Ranjbar <lranjbar@redhat.com>
> NO-ISSUE: Fix bug in the automation date for ocm tag

- src/inventory/routes.go
- src/inventory/routes_test.go
While testing the assisted-service [PR](https://github.com/openshift/assisted-service/pull/1785) I noticed that the slice returning from the agent for the default route was always empty. I tested the logic locally using my own routing information and I detected that the value returned by the go library for the destination field is a nil, and in the current filtering logic it is expecting an IP of zero value (0.0.0.0 for IPv4 and equivalent for IPv6). 
This PR addresses this discrepancy by making sure that the filter now only takes into account routing entries where the Dst field is nil, or if it's not nil, then it is unspecified (== IP zero) in order to be considered a default route.
> MGMT-6498: Fixes empty slice capturing the default route

- src/apivip_check/apivip_check.go
- src/commands/connectivity_check_test.go
- src/disk_speed_check/disk_speed_check_test.go
- src/inventory/boot_test.go
- src/inventory/interfaces.go
- src/inventory/interfaces_test.go
- src/util/network_interface.go
Fixes the following errors from the linter:
```
lranjbar@localhost assisted-installer-agent]$ make lint
golangci-lint run -v --fix
INFO [config_reader] Config search paths: [./ /home/lranjbar/github/openshift/assisted-installer-agent /home/lranjbar/github/openshift /home/lranjbar/github /home/lranjbar /home /] 
INFO [config_reader] Used config file .golangci.yml 
INFO [lintersdb] Active 16 linters: [deadcode errcheck gocyclo gofmt goimports gosec gosimple govet ineffassign scopelint staticcheck structcheck typecheck unconvert unused varcheck] 
INFO [loader] Go packages loading at mode 575 (imports|name|types_sizes|compiled_files|deps|files|exports_file) took 533.592492ms 
INFO [runner/filename_unadjuster] Pre-built 0 adjustments in 8.454188ms 
INFO [linters context/goanalysis] analyzers …
```
> NO-ISSUE Fix linting errors on ocm-2.3 branch

- Dockerfile.assisted_installer_agent
- Dockerfile.assisted_installer_agent-build
- go.mod
older versions of go are out of support, so for security compliance, we were trying to get all components on the latest version. 1.14 is already out of support, i.e. https://endoflife.date/go
> MGMT-7210 Upgrade Go version to 1.16

- src/inventory/interfaces.go
- src/inventory/routes.go
- src/inventory/routes_test.go
When the GW is returned as `nil` from the agent, it is populated as garbage (`<nil>`) in the json, instead of containing a properly formatted IP. This causes the validation in the service to dump error log messages as it is unable to parse the GW value. 
This fix tackles the parsing part from the agent side, and sends an empty string value when it detects the value of the Gateway is nil.
There is a counterpart PR for the service to handle this use case:
https://github.com/openshift/assisted-service/pull/2223
I also enhanced the unit tests to check that the contents of the processed routes match as expected.
@ori-amizur can you take a look at this PR when you have some time?
> Bug 1980901: Parse GW nil as net zero

- Makefile
- go.mod
- go.sum
- src/commands/register_node.go
- src/commands/service_api.go
- src/commands/step_processor.go
- src/config/agent_config.go
- src/config/connectivity_config.go
- subsystem/agent_test.go
- subsystem/apivip_check_test.go
- subsystem/container_image_availability_test.go
- subsystem/docker-compose.yml
- subsystem/lease_test.go
- subsystem/ntp_test.go
- subsystem/utils.go
Support both APIs.  The distiction is by the flags --cluster-id and --infra-env-id.
If --cluster-id is present then we use v1 APIs.  If --infra-env-id is present then we use
v2 APIs.
/cc @yevgeny-shnaidman
> MGMT-7383: Add v2 APIs to agent

- src/inventory/routes.go
- src/inventory/routes_test.go
Aligns the IP protocol version used to retrieve the routes with the one used in the netlink library:
* IPv4 : unix.AF_INET
* IPv6: unix.AF_INET6
This change also fixes a side effect that was caused by using the wrong IP protocol version when calling netlink's API to retrieve all the routes (`netlink.RouteList(link,IPversion)`), which lead to netlink not being able to filter out the routes correctly because of a mismatched protocol version.
https://github.com/vishvananda/netlink/blob/f5de75959ad544e80f08d6adaffa7026df3380ef/nl/nl_linux.go#L22-L23
```golang
FAMILY_V4   = unix.AF_INET
FAMILY_V6   = unix.AF_INET6
```
Currently, querying for the IPv4 routes or IPv6 routes, the API call returns all routes for all versions in the same call.
```bash
Routes for family 4
[Family 2] route {Ifindex: …
```
> Bug 1994060: Change IP version to golang's unix constant

- src/inventory/system_vendor.go
- src/inventory/system_vendor_test.go
To add oVirt provider support some modifications need to be done on the agent side.
oVirt platform is detected according to the family parameter and not by product name 
which can be various, to detect the right platform and add it to the isVitual list a new 
function was added and it will change the host product type to match oVirt one, it will
ensure that the rest of the flow will remain the same as for the different types of hosts.
> OCPRHV-591: Add oVirt support to the agent side

- go.mod
- go.sum
- src/inventory/inventory.go
- src/inventory/tpm.go
- src/inventory/tpm_test.go
The TPM version is validated in the service to make sure the specific
TPM HW is supported by openshift.
> MGMT-7457: Adding TPM version to host inventory.

- Dockerfile.assisted_installer_agent
The original plan was to move all images to ubi8. This is not possible due to the lack
of some packages that are needed for other projects. We are now going to switch all images
to stream8 with the hope that the consistency accross repos will prevent (or help) with
debugging current/future issues in CI.
The goal is to keep component's builds as consistent as possible in the channels we are
releasing them on
Signed-off-by: Flavio Percoco <flavio@redhat.com>
> MGMT-7761: Switch to stream8

- src/container_image_availability/container_image_availability.go
- subsystem/container_image_availability_test.go
Image availability command should exit failure in case images are not available. It is done to not cache failed answers and allow retry
> OCPBUGSM-34971: container image availability command should not exit 0 if it failed on one of the images

- src/logs_sender/send_logs.go
When the installer launches the logs-sender binary from the agent, we
encounter this error:
`Logs were sent\n1 error occurred:\n\t* /usr/bin/lsblk failed: 1 lsblk: unknown column:  NAME,MAJ:MIN,SIZE,TYPE,FSTYPE,KNAME,MODEL,UUID,WWN,HCTL,VENDOR,STATE,TRAN,PKNAME\n\n\n\n\n`
It is caused by the columns list and the `-o` flag being inside the same
parameter.
/cc @mkowalski
This commit separates them to avoid this error
> NO-ISSUE: Logs sender lsblk unknown column error fix

- src/agent/main/main.go
The agent binary only checked if a reboot happened when next_step_runner has
an error. This is not the case when reboots happen, next_step_runner exits
cleanly with a 0 exit code, so we should only check dry reboot in the agent
if next_step_runner had no error
> MGMT-7941: Fix agent dry reboot condition in wrong code path

- src/commands/connectivity_check.go
- src/config/dry_run_config.go
- src/inventory/dry_inventory.go
- src/inventory/inventory.go
- src/util/dependencies.go
Dry run mode was only tried so far with single-node. This commit makes
the IP and hostname configurable, allowing the swarm to launch
multi-node clusters without having hosts clash.
It also disables the connectivity check in dry run mode because with
different fake IP addresses that would obviously not work
> MGMT-7941: Allow forcing the IP address and hostname of the agent in dry mode

- src/apivip_check/apivip_check.go
- src/apivip_check/apivip_check_test.go
The CIDR validation, the majorityGroup check, and the L2 and L3 validations, are
already performed by assisted service when validating the cluster, host, and network
data. There should not be a need to replicate this validation in the agent itself.
UPDATE
==
This was manually tested by deploying a 3-masters spoke cluster and then a 1 worker (on a separate network). Tests were done by myself and @alknopfler 
Signed-off-by: Flavio Percoco <flavio@redhat.com>
>  MGMT-7847: Don't check verify CIDR in the host

- src/apivip_check/apivip_check.go
- src/apivip_check/apivip_check_test.go
Added 'Accept' to ignition download request header to explicitly specify version 3.2.0.
This is required to avoid a redundant conversion to v2.2[1] and a failure in machine-config-operator when LUKS is enabled[2].
[1] https://github.com/openshift/machine-config-operator/blob/9c6c2bfd7ed498bfbc296d530d1839bd6a177b0b/pkg/server/api.go#L154
[2] error: failed to convert config from spec v3.2 to v2.2: unable to convert Ignition spec v3 config to v2: LUKS is not supported on 2.2
> MGMT-7428: apivip_check - Accept header in ignition request

- go.mod
- go.sum
- src/apivip_check/apivip_check.go
- src/apivip_check/apivip_check_test.go
- src/commands/connectivity_check.go
- src/inventory/dry_inventory.go
Add support of Authorization token and CA cert to the API VIP connectivity validation.
Depends on https://github.com/openshift/assisted-service/pull/3027
> MGMT-8424: Add token and CA cert to API VIP check

- go.mod
- go.sum
- src/apivip_check/apivip_check.go
- src/apivip_check/apivip_check_test.go
Return ignition as part of APIVipConnectivityResponse for exposing LUKS (disk encryption) information to the
service. This is required as part of disk encryption validation for day2 hosts.
Note: pending on swagger change - https://github.com/openshift/assisted-service/pull/3073
> MGMT-7428: return ignition in apivip_check response

- go.sum
- src/apivip_check/apivip_check.go
- src/scanners/machine_uuid_scanner.go
- src/scanners/machine_uuid_scanner_test.go
In BF cards there is know serial of mother board and we get "Unspecified Base Board Serial Number" ,
we should take systemuuid in that case
> MGMT-8847: Add bf serial value to unknown serials in agent

- go.mod
- go.sum
As a follow-up to 'update golang-jwt package' in the service: https://github.com/openshift/assisted-service/pull/3108, updating the assisted-service package.
> NO-ISSUE: update assisted-service package

- src/commands/service_api.go
- src/inventory/interfaces_test.go
- src/scanners/machine_uuid_scanner.go
- src/scanners/machine_uuid_scanner_test.go
- src/util/mocks.go
[MGMT-8481](https://issues.redhat.com/browse/MGMT-9003): Allow fallback for generate uuid from mac for kaloom deployment
Currently kaloom are not able to deploy multinode cluster as their machines generates same uuid as serial uuid and mother board uuid has "Default string" value
We want to create quick fix till we fully move to using macs
> MGMT-8481: Allow fallback for generate uuid from mac for kaloom deployment

- .github/dependabot.yml
To make dependabot PRs pass lint job, we need commit messages to start with ``NO-ISSUE``.
/cc @filanov
> NO-ISSUE: fix dependabot commit messages to include NO-ISSUE

- go.mod
- src/commands/errors.go
- src/commands/register_node.go
- src/commands/step_processor.go
- src/session/inventory_session.go
The OCP router sends a 503 response with a standard HTML formatted message when the service is down.
However, the go client generated by swagger expects a JSON-formatted API message and fails to analyze the response body. The result is an unclear error message in the agent, installer, and controller when the service is down.
Based on the recommended course of action this PR replaces the consumer of text/html responses to handle all sort of embedded responses (Both text, openshift and assisted-service generated errors) so all possible 503 (and other general responses) will be covered. Since BE errors are not printed well with the generic Error() function in case of embedded reason, it also put forward a marshaling code for all sort of errors, so in all cases the logs will be informative.
> MGMT-8752: handle ocp router 503 errors

- src/inventory/disks.go
- src/inventory/disks_test.go
The agent currently returns `smartctl --xall` which returns lots of
information, some of which isn't SMART.
Let's change to `--all` instead of `--xall`.
> MGMT-7813 Reduce smartcl verbosity

- Dockerfile.assisted_installer_agent
Seems like with the move to stream8 base image, we can also RPM package for ``smartmontools`` from the official stream 8 repositories
Version installed is ``7.1-1`` which should be okay based on the comment
/cc @omertuc
> Install smartmontools from stream8 repos

- Jenkinsfile
- Makefile
Now that we have no need in bundles+indexes created by Jenkins on ocpmetal, we can completely ditch all the "publishing" parts.
This should leave the subsystem running (which we currently have no alternative to) but remove everything else that is already duplicated by other jobs/automation/etc.
/cc @eliorerz @filanov @lranjbar
> NO-ISSUE: remove Jenkins publishing step

- src/apivip_check/apivip_check_test.go
- src/scanners/machine_uuid_scanner.go
- src/scanners/machine_uuid_scanner_test.go
If the system's UUID is a special case, we fall back to using the MAC
address instead. We mistakenly used the same special cases for both
motherboard serial and UUID. This commit separates the special cases and
adds the special UUIDs for two hardware types.
> MGMT-9396: Fix UUID fallback

- Makefile
As part of moving the subsystem test to prow, we need to know when the
step that runs the test fails.
> MGMT-9344: Return non-zero exit when subsystem test fails

- Makefile
The original commit/PR doesn't mention why it's done. It takes a long time to
build this image and it's annoying to wait for it when you just want to iterate
on a few short tests
The Dockerfile should take care of updating the image if things change, we can
rely on its cache, I can't come up with a good reason to delete it
Original PR: https://github.com/openshift/assisted-installer-agent/pull/219
Original commit: bda33e2f2fc9f6f04d46d6ac90d4f04a32604517
> NO-ISSUE: Don't delete the subsystem_agent docker-compose image every time

- .ci-operator.yaml
It will enable to override the default dcoker that is used in the CI so
we will not need to make changes in severl palces
> NO-ISSUE: add ci operator file

- .ci-operator.yaml
It doesn't support pinting to a local file so the upgrade will be done
in several steps
1. update local golang version without code changes
2. update releases to a new golang verison
3. push pr for code changes
> NO-ISSUE: remove .ci-operator.yaml file

- Makefile
- subsystem/Dockerfile.agent_test
- subsystem/agent_test.go
- Agent image can be passed as environment variable while running make
command. When this changes, it has to be used in the subsystem as
well.  This change passes this variable as argument to docker build.
/cc @tsorya
> NO-ISSUE: Pass agent image name to subsystem docker file

- src/commands/reply_cache.go
- src/commands/step_processor.go
When using the combined agent, the global reply cache may suppress
repeating replies, from agents representing different hosts, since all
are running in the same process.
This change creates reply cache per step-processor which represents
single host.
/cc @omertuc
> NO-ISSUE: Create reply cache per session instead of global one

- subsystem/container_image_availability_test.go
NO-ISSUE: in ci pulling image can be too quick and we can't validate 2 running image availability commands
> NO-ISSUE: in ci pulling image can be too quick and we can't validate 2 running image availability commands

- .ci-operator.yaml
We are looking to replicate the configuration that exists in `openshift/installer` for building images in the CI.
Adding `.ci-operator.yaml` so we can set the build root to be from the repository.
[AGENT-153](https://issues.redhat.com//browse/AGENT-153)
/cc @pawanpinjarkar @andfasano
> AGENT-153: Add .ci-operator.yaml for OCP payload image

- .github/dependabot.yml
We no longer need the ok-to-test label, as dependabot is a
trusted-app.
/cc @eliorerz @filanov
> NO-ISSUE: remove redundant ok-to-test label 

- src/commands/actions/next_step_runner.go
Connectivity check spawns sub-processes proportional to the number of hosts in the cluster.
When running in a large cluster environment, connectivity check may fail due to limitation on the number of processes in a container.
Since connectivity check is part of the next-step-runner executable, the next-step-runner podman arguments will be added with
"--pids-limit=0" (unlimited)
/cc @tsorya
> MGMT-10454: Run next-step-runner with unlimited pids limit

- src/inventory/disks.go
- src/inventory/disks_test.go
Now the smart command runs "smartctl --all --quiet=errorsonly"
instead "smartctl --all --json=c"
JSON output was removed because it causes the option --quiet=errorsonly
to have no effect.
Currently the smart data is no in use anywhere, so it should not be a
problem.
/cc @avishayt
> MGMT-9505: SMART data should include only errors

- Dockerfile.assisted_installer_agent
We currently cannot access RPM for package smartmontools:
```
[MIRROR] smartmontools-7.1-8.fc32.x86_64.rpm: Status code: 404 for
https://download-cc-rdu01.fedoraproject.org/pub/fedora/linux/releases/32/Everything/x86_64/os/Packages/s/smartmontools-7.1-8.fc32.x86_64.rpm
(IP: 8.43.85.72)
```
(see
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-installer-agent-release-ocm-2.4-subsystem-test-periodic/1533970131380604928)
This is probably because F32 is EOL since 2021-05-25 so packages no
longer persistent in their registries.
Trying locally to install it, it seems like
`quay.io/centos/centos:stream8` has an updated version of the package
(>=7.1), and so the image used in CI.
> NO-ISSUE: fix smartmontools installation in U/S image

- Dockerfile.ocp
ART's tooling makes use of [bashlex](https://github.com/idank/bashlex) to parse `RUN` commands found in Dockerfiles.
But for whatever reason it is failing to parse the following instruction:
```
RUN if [[ "$(arch)" == "x86_64" ]]; then dnf install -y biosdevname && dnf clean all; fi
```
```
bashlex.errors.ParsingError: unexpected token '"$(arch)"' (position 6)
```
At some point the root cause must be addressed, but given the time constraints, I'd like to suggest the following change for now, just to make our parser happy for the time being and proceed with the onboarding of this image into OCP 4.11.
> ART-4057: Work around parsing issue on ART's tooling

- Dockerfile.ocp
dmidecode package is not available for ppc64le and s390x arches.
> ART-4057: Only install `dmidecode` on x86_64 and aarch64

- src/inventory/interfaces_test.go
- src/scanners/machine_uuid_scanner_test.go
- src/util/mocks.go
- src/util/test_utils.go
go generate command failed when the package uses the generated code
The make generate target deletes the old mocks before regenerating them
mocks.go file used util.MockInterface type so after the deletion the compilation failed which fails the mock generation for this package
Using mock.Mock embedded object instead
> NO_ISSUE: fix mock generation.

- Dockerfile.ocp
Once the images are building successfully in OSBS (and only then), they can be added to the release payload image by setting a label in the Dockerfile:
`LABEL io.openshift.release.operator=true`
> AGENT-75: Add assisted installer images into OCP playload for Agent Work

- Dockerfile.ocp
We don't actually run the agent from within the container (instead it's
first copied to the host filesystem), so specifying an ENTRYPOINT is
actually unhelpful.
> AGENT-263: Remove ENTRYPOINT from OCP Dockerfile

- src/apivip_check/apivip_check.go
Currently, we filter the ignition file by removing literally everything
from it except for a few very specific files and the LUKS information.
The resulting ignition from such filtering process is completely
unparsable by the service as it doesn't even contain which version
of ignition it is.
This means that the feature that dependened on it, such as day-2 disk
encryption, did not work.
It was also a blocker for [MGMT-10973](https://issues.redhat.com//browse/MGMT-10973) (single node imported cluster DNS
validation, see 15557354b2e2d92afa46d36004153315c30c1d16).
This commit makes it so that instead of starting with an empty ignition
and then adding just the files we want, instead we will start with a
full ignition, delete just the very heavy parts (the systemd units
and storage files), and …
> MGMT-10973: Filtered ignition should keep non-heavy elements

- src/apivip_check/apivip_check.go
When the ignition downloaded by the day-2 worker discovery indicates
that kubelet is connecting to the day-1 cluster using an IP address
rather than a domain name, we can safely disable DNS validations for
that worker in day-2.
This is the case in Hypershift.
The service should also be modified to detect this situation and disable
DNS validations when it's detected.
The agent should be modified to include /etc/kubernetes/kubeconfig in
the day-2 ignition, because right now it's omitted for size concerns
> MGMT-11262: Include `/etc/kubernetes/kubeconfig` in day-2 ignition

- src/agent/main/main.go
- src/apivip_check/main/main.go
- src/config/agent_config.go
- src/config/subprocess_config.go
- src/connectivity_check/main/main.go
- src/container_image_availability/main/main.go
- src/dhcp_lease_allocate/main/main.go
- src/disk_speed_check/main/main.go
- src/domain_resolution/main/main.go
- src/free_addresses/main/main.go
- src/inventory/main/main.go
- src/logs_sender/main/main.go
- src/next_step_runner/main/main.go
- src/ntp_synchronizer/main/main.go
- src/util/logging.go
https://issues.redhat.com/browse/MGMT-11356
Previously the agent only allowed logging to
either the journal or to a log file. This doesn't
allow logging to stdout, which is needed if the
agent runs in a pod.
This adds the option to log to stdout. This can
be specified when running the agent with the flag
`--with-stdout-logging true`
/cc @carbonin 
Tested by running the agent in a pod with the argument `-with-stdout-logging=true` in the pod spec and running `oc logs <pod name>`
> MGMT-11356: Add option to log to stdout

- Dockerfile.assisted_installer_agent-build
We sometimes get the following flake:
```
golangci/golangci-lint info checking GitHub for tag 'v1.24.0'
golangci/golangci-lint crit unable to find 'v1.24.0' - use 'latest' or
see https://github.com/golangci/golangci-lint/releases for details
```
(see https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-assisted-installer-agent-release-ocm-2.6-subsystem-test-periodic/1556051193472487424)
This means we're doing too many requests to GitHub's API and getting holded by its rate-limiter.
The suggested change is using pre-built images, which are already getting mirrored to quay.io (and to internal prow registry), hopefully getting much less problems with this setup.
> MGMT-11527: fix flaky golangci-lint installation

- src/scanners/machine_uuid_scanner.go
- src/scanners/machine_uuid_scanner_test.go
When falling back to MAC generated host UUID , we have loopback device in the list of interfaces with empty UUID
If this interface gets picked up to be the one to generate the UUID (and it does, since the sorting provokes that it ends up always being the first element), it will create always the same UUID for all hosts:
```
Aug 10 13:27:38 109-74-204-122 agent[5130]: time="10-08-2022 13:27:38" level=info msg="Using mac from interface lo to provide node-uuid" file="machine_uuid_scanner.go:118"
```
cc: @avishayt 
cc: @filanov
> MGMT-11575: Ignore empty MAC address for host UUID generation

- src/disk_speed_check/disk_speed_check.go
fio's filename can be a colon-separated list of devices to test. This however breaks some paths with colons, so these need to be escaped.
See https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename
> MGMT-11185: disk_speed_check: escape colons when calling fio

- Dockerfile.assisted_installer_agent
- Dockerfile.ocp
- Makefile
[MGMT-10936](https://issues.redhat.com//browse/MGMT-10936): Cleanup agent code for commands that are not run as with podman run anymore
> MGMT-10936: Cleanup agent code for commands that are not run as with podman run anymore

- Dockerfile.assisted_installer_agent-build
Fix getting this in some jobs:
```
go: downloading golang.org/x/sys v0.0.0-20220909162455-aba9fc2a8ff2
go: downloading golang.org/x/term v0.0.0-20201126162022-7de9c90e9dd1
go: downloading golang.org/x/term v0.0.0-20220722155259-a9ba230a4035
go: downloading github.com/vektra/mockery v1.1.2
go: downloading github.com/stretchr/testify v1.7.1
go: downloading github.com/stretchr/testify v1.8.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/stretchr/objx v0.1.1
go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: downloading github.com/stretchr/objx v0.4.0
go: downloading gopkg.in/yaml.v3 v3.0.1
/go/pkg/mod/golang.org/x/sys@v0.0.0-20220909162455-aba9fc2a8ff2/unix/syscall.go:83:7: undefined: …
```
> MGMT-12030: Pinning golang.org/x/sys dependency due to golang incompatibility

- src/ntp_synchronizer/ntp_synchronizer.go
The failure to reverse lookup doesn't cause the NTP synchronizer to fail.
/cc @filanov
> MGMT-11991: Move the reverse lookup failure message to debug in NTP synchronizer

- src/disk_speed_check/disk_speed_check.go
- src/disk_speed_check/disk_speed_check_test.go
By adding an offset, the disk_speed_check will not delete the partition table, allowing for subsequent steps to run properly
/cc @paul-maidment
> MGMT-12139: Add offset to FIO disk speed check

- src/disk_speed_check/disk_speed_check.go
- src/disk_speed_check/disk_speed_check_test.go
Running `fio` the way we do creates problems with the cleanupDevice of the assisted-installer
Let's revert the changes until we find a proper solution
> MGMT-12139: Revert disk_speed_check related changes

- Dockerfile.assisted_installer_agent
This shaves off ~50Mb from final container size:
```
$ podman images | grep quay.io/vrutkovs/assisted-installer-agent                                               
quay.io/vrutkovs/assisted-installer-agent                slim-agent              869abe541647  16 seconds ago      948 MB
quay.io/vrutkovs/assisted-installer-agent                master                  558e0ee6bd54  22 minutes ago      1.04 GB
```
> NO-ISSUE: Dockerfile: don't install docs and weak dependencies

- src/inventory/inventory.go
- src/inventory/inventory_test.go
- src/inventory/main_test.go
Currently hosts that have a forbidden name like `hostname` need to be manually renamed by users before proceeding to the installation of the cluster. That isn't convenient for users. To avoid it this patch changes the code so that the agent will replace those names with automatically generated ones from a MAC address of a network interface card of the host that has a non-local IP address.
Related: https://issues.redhat.com/browse/MGMT-8460
> MGMT-8460: Automatically rename discovered hosts

- src/session/inventory_session.go
- src/session/inventory_session_test.go
This patch changes the agent so that it will retry with an exponential backoff when the server respods with 401, 503 or 504.
Related: https://issues.redhat.com/browse/MGMT-11551
> MGMT-11551: Retry when service fails

- src/connectivity_check/connectivity_check.go
- src/connectivity_check/connectivity_check_test.go
When there is an L2 IP address conflict, resulting in an arping result similar to the one shown below, we need to ensure that this is correctly reported to asssisted-service so that we can advise the user of the issue correctly.
```arping -I eth0 192.168.150.74
ARPING 192.168.150.74 from 192.168.150.75 eth0
Unicast reply from 192.168.150.74 [00:50:56:95:BA:89]  0.685ms
Unicast reply from 192.168.150.74 [00:50:56:85:16:66]  0.837ms
Unicast reply from 192.168.150.74 [00:50:56:85:16:66]  0.754ms
```
This change will attempt to remedy this by making sure that assisted-service is aware of the IP collission so that the user may be advised. Presently we do not do this correctly due to the following issues:
1: The existing code incorrectly reuses pointers to L2Connectity and L3Connectivity …
> MGMT-11970: Ensure that we handle an IP conflict correctly.

- src/connectivity_check/connectivity_check.go
- src/connectivity_check/connectivity_check_test.go
This will fix the case that only a single result is received if the nic has several addresses.
/cc @tsorya
> MGMT-12711:  Verify that L2 connectivity checks are received grouped by ip+mac instead of just mac

- src/session/inventory_session.go
Currently the code that retries requests writes a log message that contains the response status code. But that causes a panic if there is no response, for example if the server didn't respond at all or there was a timeout. This patch fixes that issue.
Related: https://issues.redhat.com/browse/MGMT-12760
> MGMT-12760: Don't panic when retrying after no response

- src/inventory/interfaces.go
- src/inventory/interfaces_test.go
Link local addresses are not used as node addresses.  They are similar to loopback addresses.  Currently IPv6 link local addresses are removed from the inventory. This commit also removes the IPv4 link local addresses from inventory.
/cc @tsorya
> OCPBUGS-3157: The connectivity check fails if an interface has a link-local address

- src/commands/actions/tang_connectivity_check.go
- src/tang_connectivity_check/tang_connectivity_check.go
- src/tang_connectivity_check/tang_connectivity_check_test.go
The usage of HTTP client should be mocked for tests that use external URLs as a negative flow.
/assign @ori-amizur
> MGMT-12793: Tang unit tests should not query external URLs

- src/commands/step_processor.go
- src/commands/step_processor_test.go
The retry loop that was introduced in a previous patch doesn't stop when the backoff expires and the error still happens, and also when the service explicitly asks the agent to upgrade and restart. This patch fixes that.
> NO-ISSUE: Stop retry when backoff expires or context is cancelled

- src/commands/actions/inventory_cmd.go
- src/inventory/system_vendor.go
- src/inventory/system_vendor_test.go
Add more flexible virtualized environment detection.
AFAIU we only use this for stats so it should not affect adversely in case we detect different platform as virtual (or not)
/cc @tsorya
> MGMT-12537: detect virtualized environment

- src/inventory/inventory.go
- src/inventory/inventory_test.go
Currently the code that automatically renames hosts crashes when it can't find a usable NIC. This patch fixes that.
Related: https://issues.redhat.com/browse/MGMT-12827
> MGMT-12827: Don't try to rename when there is no usable NIC

- src/disk_speed_check/disk_speed_check.go
With https://github.com/openshift/assisted-installer/pull/583 we can reapply @vrutkovs's fix to disk_speed_check so FIO runs properly 
fio's filename can be a colon-separated list of devices to test. This however breaks some paths with colons, so these need to be escaped. See https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename
Previously `fio` was creating `/dev/disk/by-path/pci-0000` for `/dev/disk/by-path/pci-0000:06:0000.0` disk, which was a) testing the wrong disk speed and
b) could fill up the root partition
/cc @vrutkovs 
/cc @osherdp
> MGMT-12339: disk_speed_check: escape colons when calling fio (#427)

- go.sum
CVE-2021-4238 goutils: RandomAlphaNumeric and CryptoRandomAlphaNumeric are not as random as they should be
https://bugzilla.redhat.com/show_bug.cgi?id=2156729
Randomly-generated alphanumeric strings contain significantly less entropy than expected. The RandomAlphaNumeric and CryptoRandomAlphaNumeric functions always return strings containing at least one digit from 0 to 9. This significantly reduces the amount of entropy in short strings generated by these functions.
https://github.com/Masterminds/goutils/commit/869801f20f9f1e7ecdbdb6422049d8241270d5e1
https://pkg.go.dev/vuln/GO-2022-0411
> OCPBUGS-5714: CVE-2021-4238 assisted-installer-agent-container: goutils

- src/inventory/disks.go
- src/inventory/disks_test.go
Add multipath FC disk check to enable RHCOS installation for PowerVM with SAN disk.
Signed-off-by: CS Zhang <zhangcho@us.ibm.com>
> MULTIARCH-3239 -- Add multipath FC disk check for Power

- Dockerfile.assisted_installer_agent
dmidecode package present in only amd64/arm64 platforms only, this PR enables dockerfile to build for ppc64le/s390x archs
> Fix the upstream dockerfile build on non-x86 platform

- Dockerfile.assisted_installer_agent
- Dockerfile.ocp
- src/inventory/disks.go
- src/inventory/disks_test.go
It was originally added because we suspected slow/unhealthy user disks
were a cause for installation failures. Eventually it seemed that we
were not able to draw conclusions from the collected S.M.A.R.T. data, so
after years of being unused, and even causing confusions [1], I think
it's time we stop collecting this data.
[1] https://issues.redhat.com/browse/MGMT-7388
> Remove S.M.A.R.T. collection

- OWNERS
- OWNERS_ALIASES
Also there's no "downstream" for this Dockerfile so that label is
unnecessary
> Make the agent team be the OWNERS of the Dockerfile.ocp file

- src/connectivity_check/connectivity_check_test.go
- src/connectivity_check/connectivity_runner.go
- src/connectivity_check/connectivity_runner_test.go
- src/connectivity_check/dry_run_checkers.go
- src/connectivity_check/ipv4_arping_checker.go
- src/connectivity_check/ipv4_arping_checker_test.go
- src/connectivity_check/ipv6_nmap_checker.go
- src/connectivity_check/ipv6_nmap_checker_test.go
- src/connectivity_check/util.go
- src/connectivity_check/util_test.go
When check L2 IPv4 with ARPING, testing on interfaces that do not have valid IPv4 addresses causes the arp table to have duplicate entries, which may cause troubles in connectivity checks and packet losses. This change ensures that only interfaces with valid addresses are used for L2 check.
In addition, same restriction is applied when doing IPv6 L2 check.
/cc @filanov
> MGMT-13758: In connectivity check, ARPING checks should not run on nics without valid IPv4 address

- go.mod
- go.sum
- vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/check_page.go
- vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/controller.go
- vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/ui.go
- vendor/modules.txt
This patch is a cherry-pick from https://github.com/openshift/assisted-installer-agent/pull/512 for the release 4.13
> OCPBUGS-8490: vendor agent-installer-utils to v0.0.0-20230307094740-57807526b660 

- src/scanners/machine_uuid_scanner.go
- src/scanners/machine_uuid_scanner_test.go
We have seen different hosts with the same motherboard serial on this type of hardware, so we should ignore it and fallback to other methods of generating the host UUID.
> MGMT-13946: Ignore Proliant Gen 11 serial

- README.md
The libnmstate library has been updated from .1 to .2 (see https://issues.redhat.com/browse/ART-6481). This is used by agent-tui. Force an rebuild with a trivial change in order to pick up the updated lib.
> Force update to pick up latest libs

- src/logs_sender/mock_LogsSender.go
- src/logs_sender/send_logs.go
- src/logs_sender/send_logs_test.go
- src/util/execute.go
[MGMT-14481](https://issues.redhat.com//browse/MGMT-14481): journal logs are empty during installation on rhel9.2
Running journal logs gathering on host and not inside container
> MGMT-14481: journal logs are empty during installation on rhel9.2

- src/inventory/inventory.go
- src/inventory/inventory_test.go
Currently the host auto rename feature doesn't work for hosts that only have IP addresses in VLAN network interface cards. This patch fixes that limitation.
Related: https://issues.redhat.com/browse/MGMT-13009
> MGMT-13009: Auto rename host with VLAN

- src/inventory/disks.go
- src/inventory/disks_test.go
This change modifies the disk `checkEligibility` function to take [openshift-appliance](https://github.com/openshift/appliance)
disks into account.
In a case where the disks have partitions with the `'agent'` prefix, those disks
should be marked as eligible for installation. This is a change from the existing
behavior, that used to mark disks with mounted partitions as not eligible
for installation.
[openshift-appliance](https://github.com/openshift/appliance) is a command line utility for building a disk image that
orchestrates OpenShift installation using the Agent-based installer, mainly
with disconnected environments in mind.
Co-authored-by: Avishay Traeger <atraeger@redhat.com>
> MGMT-14540: Mark Appliance disk(s) with a partition name prefix 'agent' as eligible

- Makefile
https://issues.redhat.com/browse/MGMT-15235
In order to be FIPS compliant, we need to compile
all go code with CGO_ENABLED=1.
/cc @filanov
> MGMT-15235: Compile with CGO_ENABLED=1 for FIPS

- Makefile
https://issues.redhat.com/browse/MGMT-15235
In order to be FIPS compliant, we need to compile
all go code with CGO_ENABLED=1.
Original cherry pick from master PR failed https://github.com/openshift/assisted-installer-agent/pull/569#issuecomment-1633187103
> [release-ocm-2.6] MGMT-15235: Compile with CGO_ENABLED=1 for FIPS

- src/connectivity_check/ipv4_arping_checker.go
Newer versions of arping usually return 1 for usually spurious reasons. Previous versions never returned 1. Actual errors are indicated by returning 2 or -1.
Therefore treat return codes 0 and 1 as equivalent to give the same behaviour on RHEL 9 as on RHEL 8.
> OCPBUGS-16373: Ignore arping errors on RHEL 9

- src/commands/step_processor.go
Currently when the user deletes a host the next step runner receives a `404 Not Found` response code from the server, logs it and tries again with exponential backoff. After approximately 15 minutes it stops retrying and exits, and then the main process of the agent will register the host again. The net result is that the host is automatically re-added after those 15 minutes, and we don't want that. To avoid that this patch changes the next step runner so that it freezes the agent. To register the host again the user will have to start the agent or else reboot the host.
Related: https://issues.redhat.com/browse/MGMT-13111
> MGMT-13111: Freeze on `404 Not Found`

- src/inventory/system_vendor.go
- src/inventory/system_vendor_test.go
- src/util/dependencies.go
- src/util/mock_IDependencies.go
Look at chassis.asset_tag to check if the host (VM or BM) runs on Oracle
Cloud Infrastructure (OCI).
If we find out that the host runs on OCI, we override the manufacturer.
> MGMT-14933: Detect if the host in running on OCI

- Makefile
Reverts openshift/assisted-installer-agent#569
Multi-arch build errors occur because of the initial change.
Reverting until further investigation can be completed.
See slack thread https://redhat-internal.slack.com/archives/C014N2VLTQE/p1690385559654819
> Revert "MGMT-15235: Compile with CGO_ENABLED=1 for FIPS"

- Makefile
https://issues.redhat.com/browse/MGMT-15235
To be FIPS-compliant, CGO_ENABLED=1 flag must be
specified for go code.
This flag along with the base image used doesn't
work for architectures other than amd64.
See previous revert PR for more information
https://github.com/openshift/assisted-installer-agent/pull/582
Slack thread discussion
https://redhat-internal.slack.com/archives/C014N2VLTQE/p1690385559654819
/cc @gamli75 @filanov
> MGMT-15235: Compile with CGO_ENABLED=1 for amd64

- Makefile
https://issues.redhat.com/browse/MGMT-15235
To be FIPS-compliant, CGO_ENABLED=1 flag must be
specified for go code.
This PR introduces the CGO_FLAG for builds that
need to change what CGO_ENABLED is set to
such as the ACM builds.
AMD64 builds will always set the CGO_FLAG to 1
for FIPs, which translates to CGO_ENABLED=1.
----------------------
See slack thread for more information:
https://redhat-internal.slack.com/archives/C05BCTGEGAK/p1691607687429729?thread_ts=1691590437.166799&cid=C05BCTGEGAK
/cc @filanov @gamli75 @smithbw88
> MGMT-15235: Allow setting CGO_ENABLED flag

- Makefile
- src/inventory/disks.go
- src/tang_connectivity_check/tang_connectivity_check_test.go
For some reason we applied ``--fix`` to the lint code, which fixes the issues and return a 0 code (so the job always passes).
This removes it and fixes the lint issues in code.
> NO-ISSUE: fix lint target and code

- Dockerfile.assisted_installer_agent-build
- src/free_addresses/free_addresses.go
- src/inventory/disks.go
- src/tang_connectivity_check/tang_connectivity_check_test.go
- src/util/network.go
Cannot update golangci-lint in the same PR as one exhibiting issues because the CI still uses the previous version.
Updating k8s.io/apimachinery module to a newer version causes the old linter to throw nil pointer error.
Example [PR#590](https://github.com/openshift/assisted-installer-agent/pull/590)
Includes formatting changes by the linter.
> OCPBUGS-16482: bump golangci-lint to v1.53.1

- Dockerfile.assisted_installer_agent
- Dockerfile.assisted_installer_agent-build
- subsystem/Dockerfile.agent_test
- subsystem/lease_test.go
Now that D/S building system fully supports RHEL-9 base images (and allows easy installation of nmstate and other libs that were previously unsupported) we can move U/S to stream9 and D/S to ubi9-minimal.
It doesn't seem possible to easily use ubi9-minimal U/S for the assisted-service, because installation of nmstate packages either requires entitlements running on a RHEL node, or alternatively an access to RedHat's internal network (which can be a major problem for U/S development). For a better consistency we're sticking with the same for the agent, installer, etc.
> MGMT-15809: change base image to stream9

- Dockerfile.assisted_installer_agent
- Dockerfile.ocp
- Makefile
- src/agent/main/main.go
- src/disk_speed_check/main.go
- src/free_addresses/main.go
- src/inventory/main.go
- src/logs_sender/main.go
- src/next_step_runner/main.go
[MGMT-16011](https://issues.redhat.com//browse/MGMT-16011)
See commit message for information on what changed
From **606MB** to **315MB** (48% reduction)
* **245MB** dnf installations layers
* **207MB** agent binaries (**53MB** + **13MB** + **14MB** + **56MB** + **59MB** + **12MB**)
* **118MB** dnf installations layer
* **42MB** agent binary
65% reduction in added size.
* Half the total size is now just the base image
* It's difficult to make the agent binary any smaller, go binaries are just big
* 50% of the size DNF installations layer is just podman which is not something we can replace
* The rest of the dnf installations layer is full of small tools we rely on
We need to perform similar work also on the downstream Dockerfile, which creates images that weigh much more
> Shrink agent image

- Makefile
this build tag would enable FIPS or Die functionality in binaries
/cc @adriengentil
> MGMT-15860: add strictfipsruntime to build

- src/inventory/disks.go
- src/inventory/disks_test.go
In order to support deploying the appliance on a vSphere env, set the HasUUID property on the appliance fake disk. I.e. use the 'hasUUID' func that handles vSphere disks.
> MGMT-16335: set HasUUID on appliance mock disk

- Dockerfile.assisted_installer_agent-build
app-sre made their repo mirroring golangci-lint private for legal reasons, and
now our jobs are failing to install it. Installing it now from the cli.
We could also have pulled golangci-lint from dockerhub, but rate
limitation there is quite aggressive.
> [release-ocm-2.9] MGMT-16370: fix golangci-lint failing to be pulled

- Dockerfile.assisted_installer_agent-build
app-sre made their repo mirroring golangci-lint private for legal reasons, and
now our jobs are failing to install it. Installing it now from the cli.
We could also have pulled golangci-lint from dockerhub, but rate
limitation there is quite aggressive.
> [release-ocm-2.8] MGMT-16370: fix golangci-lint failing to be pulled

- Dockerfile.assisted_installer_agent-build
app-sre made their repo mirroring golangci-lint private for legal reasons, and
now our jobs are failing to install it. Installing it now from the cli.
We could also have pulled golangci-lint from dockerhub, but rate
limitation there is quite aggressive.
> [release-ocm-2.7] MGMT-16370: fix golangci-lint failing to be pulled

- go.mod
- go.sum
- vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go
- vendor/github.com/docker/docker/api/types/filters/parse.go
- vendor/github.com/docker/docker/api/types/registry/registry.go
- vendor/modules.txt
Cherry pick of PR https://github.com/openshift/assisted-installer-agent/pull/656
https://issues.redhat.com/browse/MGMT-14226
Upgrades go dependency github.com/docker/docker to 20.10.24 to fix CVE. GHSA-33pg-m6jh-5237
/cc @gamli75
> [release-ocm-2.9] MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842 (#656)

- src/commands/actions/install_cmd.go
- src/commands/actions/install_cmd_test.go
If golang boolean flag has value, it must appear in the form '--flag=<value>'.  In our case the value 'true' was appended after space which caused the flag parser in assisted-installer to stop parsing. This caused all the flags after this flag to be ignored which were the proxy flags.
/cc @avishayt
> MGMT-16459: [STG] Cluster 4.15.0-rc.0 with HTTP Proxy failed on timeout due the failed to StartContainer for etcd with CrashLoopBackOff

- subsystem/agent_test.go
- subsystem/container_image_availability_test.go
when pulling the image using Docker it create a validation error 
```console
> docker pull quay.io/aptible/hello-world                                                                                     
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of qua
y.io/aptible/hello-world:latest to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/ 
```
> NO-ISSUE: subsystem test failing due image format version

- OWNERS_ALIASES
- go.mod
- go.sum
- vendor/github.com/opencontainers/runc/libcontainer/user/user.go
- vendor/modules.txt
Bump runc to v1.1.12 to mitigate CVE-2024-21626
> MGMT-16587: Bump runc to v1.1.12 to mitigate CVE-2024-21626

- Dockerfile.assisted_installer_agent-build
The reference to the quay image has been replaced with RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/bin v1.53.2 Which installs v1.53.2 of `golangci-lint` into the skipper build container. If we leave this unchanged, the skipper build container fails with an error about a missing image.
> MGMT-17541: Replace broken golangci reference

- src/inventory/disks.go
- src/inventory/disks_test.go
Depending on machine configuration internal disks may appears as
removable.
Let's drop this check to un-block installations in such setup.
> OCPBUGS-33404: Make removable disks eligible

- Dockerfile.assisted_installer_agent
[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
> [release-ocm-2.9] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid

- Dockerfile.assisted_installer_agent
[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
> [release-ocm-2.8] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid

- Dockerfile.assisted_installer_agent
[CentOS Linux 8 had reached the End Of Life (EOL)](https://www.centos.org/centos-linux-eol/) on December 31st, 2021. It means that CentOS 8 will no longer receive development resources from the official CentOS project. After Dec 31st, 2021, if you need to update your CentOS, you need to change the mirrors to [vault.centos.org](https://vault.centos.org/) where they will be archived permanently. Alternatively, you may want to [upgrade to CentOS Stream](https://techglimpse.com/convert-centos8-linux-centosstream/).
from - https://techglimpse.com/failed-metadata-repo-appstream-centos-8/
> [release-ocm-2.7] NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid

- .golangci.yml
- Dockerfile.assisted_installer_agent-build
- Makefile
- subsystem/utils.go
- Use centos stream 9 as the base image for test container
- Replace golang base image as it is based on centos linux 7 (EOL)
- Replace deprecated `scopelint`
> [release-ocm-2.8] MGMT-18332: Use centos stream 9 as the base image for test container

- .golangci.yml
- Dockerfile.assisted_installer_agent-build
- Makefile
- subsystem/utils.go
- Use centos stream 9 as the base image for test container
- Replace golang base image as it is based on centos linux 7 (EOL)
- Replace deprecated scopelint
> [release-ocm-2.9] MGMT-18332: Use centos stream 9 as the base image for test container

- .golangci.yml
- Dockerfile.assisted_installer_agent-build
- Use centos stream 9 as the base image for test container
- Replace deprecated `scopelint` linter
> [release-ocm-2.10] MGMT-18332: Use centos stream 9 as the base image for test container

- .golangci.yml
- Dockerfile.assisted_installer_agent-build
- Use centos stream 9 as the base image for test container
- Replace deprecated scopelint linter
> MGMT-18332: Use centos stream 9 as the base image for test container

- Dockerfile.assisted_installer_agent
- Dockerfile.assisted_installer_agent-build
- subsystem/Dockerfile.agent_test
- subsystem/lease_test.go
This PR moves centos base image from stream8 to stream 9 as well as stream8 is EOL
> [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- Dockerfile.assisted_installer_agent
- Dockerfile.assisted_installer_agent-build
- subsystem/Dockerfile.agent_test
- subsystem/lease_test.go
This PR moves centos base image from stream8 to stream 9 as well as stream8 is EOL
> [release-ocm-2.8] MGMT-18313: Replace golang base image as it is based on Centos Linux 7

- subsystem/ntp_test.go
Fix issue where the IP of the NTP source has a domain and cannot be matched to the IP set
```console
> nslookup security.cloudflare-dns.com
...
...
Name:	security.cloudflare-dns.com
Address: 1.1.1.2
```
- move all subsystem test IP's to internal local IP's
> MGMT-18521: fix NTP sources are not valid

- Dockerfile.assisted_installer_agent
The image registry.access.redhat.com/ubi9/go-toolset:1.20 does not default to the root user as registry.ci.openshift.org/openshift/release:golang-1.20 used to This results in a permissions issue when attempting to run `go mod download`
By setting the user directive prior to this operation, this PR resolves that issue
> MGMT-18837: Fix broken build due to base image change.

- src/commands/actions/download_boot_artifacts_cmd.go
- src/commands/actions/reboot_for_reclaim.go
Fixing boot issue for Z hosts in reclaim
- Removed single quotes for coreos.live.rootfs_url in bootLoaderConfigTemplate
- Added zipl incase of s390x for handling boot issue in reclaiming agents (HCP)
> MGMT-17103: Fixing boot issue for IBMZ hosts in reclaim

- .github/dependabot.yml
- Improve dependabot groups.
Allowing security update in a separate group give us smaller change ( minor version change ) which will be easier to auto merge.
> MGMT-18466: improve depndabot grouping

- src/commands/actions/download_boot_artifacts_cmd.go
Cherry-pick of PR https://github.com/openshift/assisted-installer-agent/pull/778
/cc @gamli75 
---
Adds a retry when downloading the boot artifacts from assisted service in case there are connection issues or a server disruption.
> [release-ocm-2.11] MGMT-18839: Retry downloading boot artifacts (#778)

- src/commands/actions/download_boot_artifacts_cmd.go
- src/commands/actions/reboot_for_reclaim.go
- src/commands/actions/reboot_for_reclaim_test.go
- Updated bootLoaderConfigTemplateS390x to add ai.ip_cfg_override to take care of IP and nameserver parameters , which is a mandatory parameter in z/VM as mac address is not persistent. 
- Updated paramaters which are being passed to zipl , to include parameters from /proc/cmdline which will help in reusing the agents after reclaim.
> ACM-15078: Fixing agents reuse problem in z/VM after reclaim

- src/inventory/disks.go
- src/inventory/disks_test.go
This PR adds 2 checks before making iSSI disks be be eligible as
installation disk.
[MGMT-18464](https://issues.redhat.com//browse/MGMT-18464): Check the state of the disk, we need to ensure that it is
"running" otherwise the installtion of RHCOS will fail on the disk.
[MGMT-18464](https://issues.redhat.com//browse/MGMT-18464): Check if the discovery as been booted using iBFT, this check
ensure that the iSCSI disk is actually a disk on which we will be able
to boot from.
> MGMT-18464: MGMT-18452: Add validations to make iSCSI disk eligible

- Dockerfile.assisted_installer_agent-mce
As part of migrating to konflux, we need to update our downstream dockerfiles for mce and put them in our upstream repos.
Part-of [MGMT-19371](https://issues.redhat.com//browse/MGMT-19371)
> MGMT-19371: Add downstream dockerfile for mce

- .tekton/assisted-installer-agent-mce-downstream-main-pull-request.yaml
- .tekton/assisted-installer-agent-mce-downstream-main-push.yaml
Update the tekton pipelines used to build mce downstream images to be multi-arch.
Part-of [MGMT-19390](https://issues.redhat.com//browse/MGMT-19390)
> MGMT-19390: Update mce's tekton pipelines to be multi-arch

- src/connectivity_check/connectivity_check.go
- src/connectivity_check/connectivity_runner.go
- src/connectivity_check/mtu_checker.go
- src/connectivity_check/mtu_checker_test.go
- src/connectivity_check/util.go
- src/connectivity_check/util_test.go
As part of the MTU validation implementation, the agent will include the MTU checker in the connectivity check. It will send reports to the service if a ping with the specified MTU size fails.
> MGMT-19166:  Implement MTU checker

- .tekton/assisted-installer-agent-downstream-main-pull-request.yaml
- .tekton/assisted-installer-agent-downstream-main-push.yaml
- .tekton/assisted-installer-agent-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-installer-agent-mce-downstream-2-13-push.yaml
- .tekton/assisted-installer-agent-mce-downstream-main-pull-request.yaml
- .tekton/assisted-installer-agent-mce-downstream-main-push.yaml
A lot of time our pipelines as well as other teams' pipelines are stuck because they are unable to provision hosts with different architectures to build the images.
Because we currently don't use the multi-arch images we build with konflux, we will stop building multi-arch for now and readd those architectures when we need them.
Part-of [MGMT-19507](https://issues.redhat.com//browse/MGMT-19507)
> MGMT-19507: Stop using multi-arch builds in konflux

- src/scanners/machine_uuid_scanner.go
- src/scanners/machine_uuid_scanner_test.go
As mentioned in the bug, it seems it was reported for System x3850 X5 / x3950 X5 model 71455RG
> OCPBUGS-35716: expand unknown mb serials with "(none)"

- src/connectivity_check/connectivity_check_test.go
- src/connectivity_check/ipv4_arping_checker.go
- src/connectivity_check/ipv4_arping_checker_test.go
- arping is running on interfaces that are not in the same address range as the remote IP. 
In some proxy-arp enabled networks this causes false-positive IP duplication error.
This PR will validate the remote IP is in the same network as the outgoing interface
> NO-ISSUE: OCPBUGS-43352 calculate outgoing interface for arping

- .tekton/assisted-installer-agent-downstream-main-push.yaml
Our integration environment uses latest tags, so we need the push-event pipelines to also push latest tag.
Part-of [MGMT-19595](https://issues.redhat.com//browse/MGMT-19595)
> MGMT-19595: Push latest tag for downstream image after merge to konflux int repo

- Dockerfile.assisted_installer_agent-downstream
- Dockerfile.assisted_installer_agent-mce
Currently our base images use ubi9 and MintMaker wants to upgrade it to 9.5, because MintMaker looks at the repo and tries to upgrade to the newest tag.
This changes the base image to use a repo that is just for rhel9.4.
Part-of [MGMT-19381](https://issues.redhat.com//browse/MGMT-19381)
> MGMT-19381: Change downstream base images to rhel9.4 instead of ubi9

- src/inventory/cpu.go
- src/inventory/cpu_test.go
For s390x architectures lscpu does not return the clock speed by "CPU MHz" or "CPU max MHz" field but have two fields (CPU static MHz and CPU dynamic MHz). 
"CPU static MHz" is the field representing the designed clock speed whereas the "CPU dynamic MHz" is representing the current CPU speed (throttled or energy saving).
New test case for s390x architecture was added. 
In addition the machine type was fixed, too.
The fix was tested using unit tests:
JUnit path was configured: ./junit_unit_test.xml
JUnit report was created: /root/code/Assisted_Installer/latest/assisted-installer-agent/src/inventory/junit_unit_test.xml
Ran 121 of 121 Specs in 0.268 seconds
SUCCESS! -- 121 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestInventory (0.30s)
> OCPBUGS-45910: Fix cpu clockspeed for s390x

- .tekton/assisted-installer-agent-downstream-main-pull-request.yaml
- .tekton/assisted-installer-agent-downstream-main-push.yaml
Currently downstream images are only built for x64, but we need to build for arm, s390x and ppc64le as well.
These downstream images are going to be used by SaaS.
> NO-ISSUE: Make konflux builds for downstream images to be multi-arch

- Dockerfile.assisted_installer_agent-downstream
We remove a lot of things from the final image, because they are not needed by our app.
But those things are needed for the preflight check to validate our image, so we should stop deleting them.
> NO-ISSUE: Stop removing stuff from the downstream image that are needed for preflight-check to succeed

- .tekton/assisted-installer-agent-downstream-main-pull-request.yaml
- .tekton/assisted-installer-agent-downstream-main-push.yaml
- .tekton/assisted-installer-agent-mce-downstream-2-13-pull-request.yaml
- .tekton/assisted-installer-agent-mce-downstream-2-13-push.yaml
- .tekton/assisted-installer-agent-mce-downstream-main-pull-request.yaml
- .tekton/assisted-installer-agent-mce-downstream-main-push.yaml
The current buildah images in the tekton pipelines accidentally create the SBOM with CycloneDX 1.6 which causes a violation in the ECP check.
These new images set the CycloneDX to 1.5 as the ECP check expects.
> NO-ISSUE: Update buildah image to fix a bug with SBOM

- src/commands/actions/install_cmd.go
Previously, there was a timeout of 30 seconds when pulling the installer image. This is not enough
time to pull the image and to mark the installation as failed.
This change increases the timeout to 600 seconds
(10 minutes), which is more accurate for a failed
image pull. The error message from failing to pull has also been updated to reflect the actual failure.
/cc @omertuc
> NO-ISSUE: Increase image pull timeout during install

- Dockerfile.assisted_installer_agent
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
> MGMT-19819: Add the commit reference from which the image is built to the image

- Dockerfile.assisted_installer_agent
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
> [release-ocm-2.10] MGMT-19819: Add the commit reference from which the image is built to the image

- Dockerfile.assisted_installer_agent
Currently, in most of assisted installer components CI images we don't have a way to tell from which commit reference the image was built. Since We use an image stream for each component, and we import these streams from one CI component configuration to another, we might end up with images to are not up-to-date. In this case, we would like to have the ability to check if this is actually the case.
> [release-ocm-2.9] MGMT-19819: Add the commit reference from which the image is built to the image

- src/inventory/inventory.go
- src/inventory/inventory_test.go
Tested with libvirt by creating a VM with 2 network interfaces. Then inside the VM, the bond was created manually with nmcli following [this](https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/configuring_and_managing_networking/configuring-network-bonding_configuring-and-managing-networking#configuring-a-network-bond-by-using-nmcli_configuring-network-bonding) 
I only tried the `active-backup` mode, not sure if it could have an impact
> MGMT-19588: Also use bond interface for hostname workaround

- src/connectivity_check/mtu_checker.go
- src/connectivity_check/mtu_checker_test.go
This PR updates the MTU check to apply only to MTUs != 1500. Additionally, it adjusts the header subtraction to account only for IPv4/IPv6 headers.
/cc @zaneb @AlonaKaplan
> MGMT-19927: Modify MTU Check to Only MTUs  != 1500

- src/scanners/machine_uuid_scanner.go
- src/scanners/machine_uuid_scanner_test.go
Certain hardware sets the Motherboard serial number to "-" if not configured. This should be skipped when generating the host UUID to prevent all hosts generating the same UUID.
> MGMT-20227: Skip Motherboard serial if set to "-"

- src/session/inventory_session.go
When the agent reaches out to the service, it uses the --cacert parameter passed to it and uses only the certificates in that file.
On SaaS, this parameter is usually not passed and the agent uses the system certs, which work because our SaaS is signed by a public CA.
On Kube-API, the agent is configured with a CA certificate that corresponds to the cluster's ingress. This is because the agent reaches the service through the cluster's ingress load balancer.
Some users like configuring a different CA certificate for their cluster's ingress. Ideally we should identify that automatically and pass those certs to the agent as `--cacert`, but until then users can simply use our `AdditionalTrustBundle` parameter and add their certs to make it work.
The `--cacert` parameter still contains the …
> MGMT-20868: trust also system certs

- src/inventory/routes.go
- src/inventory/routes_test.go
Before this fix, if a node had a special route like `route add -host 64.1.2.3 reject`, the agent failed to get the route’s link name and stopped collecting any routes. 
This resulted in an empty route list in the inventory and caused the host to fail validation. 
Now, if one route causes an error, we log it and skip it. so the rest of the routes are still collected correctly.
> MGMT-20023: Route inventory deleted when route without next hop interface

- src/commands/actions/next_step_runner.go
When hostname changed from node, the inventory get host does not update the service. On hostname action , linux updates /proc/sys/kernel/hostname file on node but it does not update the kernel hostname on next_step_runner container.
Due to this issue manual hostname update or changes after starting next_step_runner never reflected unless we restart agent.
In order to fix it added to next_step_runner --uts=host flag. With this flag changes on /proc/sys/kernel/hostname reflected to the container path.
> MGMT-20669: Fix hostname update for inventory get host
