openshift/assisted-installer-agent

subsystem/docker-compose.yml
=> Fix subsystem docker-compose file to override firewalld network block

src/scanners/machine_uuid_scanner.go
=> MGMT-1861 Remove the warning log from agent about not being able to find motherboard serial number

subsystem/agent_test.go
=> Avoid subsystem failure when running on system that only virtual nics have IP addresses

Dockerfile.assisted_installer_agent, Makefile, src/commands/inventory.go, subsystem/Dockerfile.agent_test, subsystem/docker-compose.yml
… and add Dockerfile for subsystem testing that adds docker installation
This will cause that docker will be installed in a container only for subsystem testing.
/cc @romfreiman 
/cc @ronniel1 
/cc @eranco74
=> MGMT-1912 Remove docker install from Dockerfile.assisted_installer_agent

subsystem/agent_test.go
=> Add additional timeout for getting inventory so subsystem test could work on weak machines

src/commands/register_node.go, src/commands/step_processor.go, subsystem/utils.go
=> Improve logging.  Session #2

subsystem/agent_test.go
=> Add timeout to wait for wiremock in order to avoid test failures on weak machines

src/free_addresses/free_addresses.go
@ori-amizur @ronniel1 please approve
=> NO-ISSUE dummy commit for DS images

src/commands/step_processor.go
=> OCPBUGSM-18606 Improve log messages for failed step replies

src/dhcp_lease_allocate/lease.go
=> OCPBUGSM-18605 Clearer dhclient timeout message

go.mod, go.sum, src/inventory/disks.go, src/inventory/disks_test.go
=> MGMR-2420 Add bootable flag to disk in inventory

Dockerfile.assisted_installer_agent, subsystem/Dockerfile.agent_test, subsystem/agent_test.go
* update base image to centos 8
* not skipping the test with free-addresses verification
=> MGMT-2578 use centos 8 as base image

src/logs_sender/send_logs.go
=> NO-ISSUE: Adding to logs the output of /usr/local/bin/installer-gather.sh

OWNERS_ALIASES
He no longer works with the AI team
=> NO-ISSUE - Remove masayag from OWNERS_ALIASES

src/inventory/disks.go
We have many reasons to skip disks as installation candidates - we will now log all the reasons why skip a certain disk when we do, to aid in troubleshooting installation problems
=> MGMT-2951 - Will log reasons for why disks were skipped

src/logs_sender/send_logs.go
Used coredumpctl to fetch all coresumps.
=> MGMT-2858: LogSender - use coredumpctl

Dockerfile.assisted_installer_agent-build
To avoid docker hub limitations
=> Use quay.io/app-sre/golang for build container

src/inventory/dependencies.go, src/inventory/disks.go, src/inventory/disks_test.go, src/inventory/memory.go, src/util/logging.go
=> MGMT-3257: discarding disks of type ODD (Optical Disk Drive)

go.mod, go.sum, src/inventory/disks.go, src/inventory/disks_test.go
Agent will just mark disks as ineligible instead of filtering them out completely.
=> MGMT-3291 - Show all disks - mark eligibility instead of filtering

subsystem/ntp_test.go
NTP tests were flaky because if we don't kill the agent, it might send getNextSteps,
after we did reset to all requests and stubs, and before we define new stubs.
Then we might get 404 for getNextSteps, while NTPResponse is expected.
Stopping the agent lets us synchronize the test scenario and the agent flow.
/cc @ori-amizur  @empovit
=> Bugfix NTP subsystem tests - reset agent

Makefile
=> NO-ISSUE Add git_revision label to the image

src/inventory/disks_test.go
=> NO-ISSUE disk unit test refactor

Dockerfile.assisted_installer_agent, scripts/installer/ovs-installer-gather.sh, scripts/installer/ovs-master-installer-gather.sh, src/logs_sender/send_logs.go
=> MGMT-4117 ovs logs gather

go.mod, go.sum, src/inventory/gpu.go, src/inventory/gpu_test.go, src/inventory/inventory.go, subsystem/agent_test.go
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
=> MGMT-4142 Detect GPU devices

src/disk_speed_check/main/main.go
=> MGMT-4397 Fix command args of disk_speed_check

go.mod, go.sum, src/inventory/disks.go, src/inventory/disks_test.go, src/scanners/machine_uuid_scanner.go, src/scanners/machine_uuid_scanner_test.go
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
=> NO-ISSUE Bump github.com/jaypipes/ghw from 0.6.1 to 0.7.0

go.sum, src/inventory/disks.go, src/inventory/disks_test.go
Use the regular path in case of duplicate by-path value
=> OCPBUGSM-27560 Duplicate installation disk

go.mod, src/commands/reply_cache.go, src/commands/step_processor.go
In case a previous result exists in the cache and it is the same as the current result, do not send to the assisted service
/cc @tsorya
=> MGMT-6484 [WIP] Create cache for post step reply api calls

src/commands/connectivity_check.go
- This will be more suitable for comparison of the results of same step-type, and maybe avoid
sending repeating step-reply to the assisted service
/cc @tsorya
=> MGMT-6656 Sort connectivity check replies before returning the results

src/apivip_check/apivip_check.go, src/commands/connectivity_check_test.go, src/commands/step_processor.go, src/disk_speed_check/disk_speed_check_test.go, src/inventory/boot_test.go, src/inventory/interfaces.go, src/inventory/interfaces_test.go, src/util/network_interface.go
As shown from fixing the linter job https://github.com/openshift/release/pull/18965
=> NO-ISSUE: Fix linter errors

OWNERS, OWNERS_ALIASES
=> NO-ISSUE: Update ocm-2.3 branch with limited approvers

OWNERS, OWNERS_ALIASES
Following #189, doing it more clear imho.
/cc @ronniel1 @jordigilh @YuviGold 
/hold
=> fix OWNERS files to match group members roles

src/commands/register_node.go, src/commands/service_api.go, src/commands/step_processor.go, src/config/agent_config.go
Remove V1 APIs of the following:
Register, GetNextSteps, PostStepReply
/cc @yevgeny-shnaidman
=> MGMT-7407: Remove V1 APIs from agent

src/inventory/routes.go, src/inventory/routes_test.go
This PR addresses 2 issues:
* Agent is unable to interpret routing entries with multipath for balancing the routing traffic
* Netlink is incorrectly including IPv6 entries for IPv4 when multipath is used. This causes the destination and gateway IPs to be mixed up because the logic defaults the destination IP to the zero IP when it's nil:
```
$> ip -4 route
default via 10.19.32.254 dev ens1f0 proto dhcp metric 100 
10.19.32.192/26 dev ens1f0 proto kernel scope link src 10.19.32.201 metric 100 
10.88.0.0/16 dev cni-podman0 proto kernel scope link src 10.88.0.1 linkdown 
```
```
$> ip -6 route
::1 dev lo proto kernel metric 256 pref medium
2620:52:0:1343::/64 dev ens1f0 proto ra metric 100 pref medium
fe80::/64 dev ens1f0 proto kernel metric 100 pref medium
fe80::/64 dev ens1f1 proto kernel …
```
=> Bug 1990060: Host returns no routes with multipart

OWNERS_ALIASES
=> MGMT-7597: Remove ronniel1, and razregev from OWNERS

go.sum, src/inventory/memory.go, src/inventory/memory_test.go, src/util/dependencies.go, src/util/mock_IDependencies.go
=> MGMT-5400: Get physical_bytes from ghw if dmidecode was failed

src/apivip_check/apivip_check.go
Signed-off-by: Flavio Percoco <flavio@redhat.com>
=> MGMT-7847: Add a deprecation warning for the VerifyCidr option

OWNERS_ALIASES
Signed-off-by: Flavio Percoco <flavio@redhat.com>
=> NO-ISSUE: Add flaper87 to approvers list

src/inventory/disks.go, src/inventory/disks_test.go
List only physical disks on inventory. Ignore LVM and other volumes.
=> OCPBUGSM-37106: List only physical disks on inventory.

src/inventory/disks.go, src/inventory/disks_test.go
Properly report iSCSI and DeviceMapper devices, and allow installation
on DeviceMapper devices.
=> MGMT-9043: Set multipath device as eligible

.ci-operator.yaml
it will enable to use local dockerfile from the pr branch so all
dependencies will be updated only in the repo
=> NO-ISSUE: replace .ci-operator.yaml to use local dockerfile

go.mod, go.sum, src/commands/actions/install_cmd.go, src/commands/actions/install_cmd_test.go, src/commands/actions/logs_gather.go, src/commands/actions/logs_gather_test.go, src/commands/actions/next_step_runner.go, src/commands/actions/next_step_runner_test.go
[MGMT-9451](https://issues.redhat.com/browse/MGMT-9451): Latest api fixes and moving to master branch of service models
=> MGMT-9451: Latest api fixes and moving to master branch of service models

src/commands/runner.go, src/commands/step_processor.go, src/next_step_runner/main/main.go
- Create runner interface that encapsulates running operation
- Create runner implemntation which is compatible with current
implementation and make it the current implemntation for running tools
in next step runner
/cc @omertuc 
/cc @filanov
=> MGMT-9807: Enable next step runner to run tools directly in addition to the running them in container

src/agent/agent.go, src/agent/main/main.go, src/commands/actions/next_step_runner.go, src/commands/actions/next_step_runner_test.go, src/commands/runner.go, src/commands/step_processor.go, src/next_step_runner/main/main.go
Run next step runner from executeRunner object implemening Runner
interface
/cc @omertuc 
/cc @filanov
=> MGMT-9806: Enable unifying agent and next step runner

go.mod, go.sum
This is a cherry-pick of https://github.com/openshift/assisted-installer-agent/pull/324
=> [release-ocm-2.5] NO-ISSUE: bump assisted-service version

src/commands/actions/action.go, src/commands/actions/api_vip_connectivity_check.go, src/commands/actions/connectivity_check_cmd.go, src/commands/actions/dhcp_leases_cmd.go, src/commands/actions/disk_perfomance_check_cmd.go, src/commands/actions/domain_resolution_cmd.go, src/commands/actions/free_addresses_cmd.go, src/commands/actions/image_availability_cmd.go, src/commands/actions/install_cmd.go, src/commands/actions/inventory_cmd.go, src/commands/actions/logs_gather.go, src/commands/actions/next_step_runner.go, src/commands/actions/ntp_sync_cmd.go, src/commands/actions/stop_installation.go
=> NO-ISSUE: Capitalize ValidateCommon to enable accessing it externally

src/util/logging.go
=> NO-ISSUE:  Add utility function that creates custom journaled logger with specific host id.

src/agent/agent.go, src/commands/runner.go, src/commands/step_processor.go, subsystem/utils.go
As we are removing command from step in service , doing cleanup in agent
=> MGMT-10154: Remove usage of command on step object

src/commands/actions/next_step_runner.go, src/commands/actions/next_step_runner_test.go
Adding mount that was removed by mistake
=> MGMT-10514: additional NTP source failed to sync

go.mod, go.sum, src/commands/actions/install_cmd.go, src/commands/actions/install_cmd_test.go, src/commands/step_processor.go, vendor/github.com/openshift/assisted-service/models/host.go, vendor/github.com/openshift/assisted-service/models/host_validation_id.go, vendor/github.com/openshift/assisted-service/models/install_cmd_request.go, vendor/github.com/openshift/assisted-service/models/interface.go, vendor/github.com/openshift/assisted-service/models/step.go, vendor/modules.txt
[MGMT-10003](https://issues.redhat.com//browse/MGMT-10003): save-partlabel and save-partindex coreos-installer args are not honored because the partition is formatted previously (#469)
If skip-installation-disk-cleanup is set path it to installer command
=> MGMT-10003:     If skip-installation-disk-cleanup is set path it to installer command

src/commands/actions/install_cmd_test.go
Mainly a dummy PR to trigger image promotion to MCE 2.1.
/cc @eliorerz @tsorya
=> NO-ISSUE: fix typo in word 'prerelease'

src/apivip_check/apivip_check.go
During day-2 installations, we want the service to optionally perform
DNS validations when the worker attempts to join none-platform clusters.
When the cluster is imported via our `.../v2/clusters/import` endpoint,
we have no way to know whether that cluster is a none-platform cluster
or cluster with managed networking (e.g. baremetal), so we have no way
to know whether we should perform the DNS validation or not. We wouldn't
like to have that validation on all the time, because it's unnecessarily
annoying for clusters with managed networking.
As part of our existing API connectivity-check, the service asks the
agent to download the worker.ign file from the to-be-joined-cluster's
machine-config-server, then send that back to the service.
The contents of that file include information that …
=> MGMT-10973: Copy coredns & keepalived static pod manifests in day-2 connectivity-check ignition

src/inventory/routes.go, src/inventory/routes_test.go, src/logs_sender/send_logs.go
[MGMT-11012](https://issues.redhat.com//browse/MGMT-11012): Add route metric to inventory
NO-ISSUE: fixing logs file permissions
=> MGMT-11012: Add route metric to inventory

src/container_image_availability/container_image_availability_test.go
=> NO-ISSUE: Fix type on convertStringArrayToInterfaceArray

src/commands/actions/download_boot_artifacts_cmd.go
[MGMT-10738](https://issues.redhat.com/browse/MGMT-10738)
https://github.com/openshift/assisted-installer-agent/pull/415
Adds a secure transport option when downloading boot artifacts
that was missing in the first PR.
=> MGMT-10738: Include secure transport for downloading boot artifacts

src/apivip_check/apivip_check.go, src/apivip_check/apivip_check_test.go
Implement service API introduced in
https://github.com/openshift/assisted-service/commit/d21ae1ef34e6cda0e613a89590bc284c59d7bf4a
=> MGMT-11447: Agent should report error when trying to pull ignition

src/inventory/disks.go, src/inventory/disks_test.go
Currently disks with mounted partitions are considered as eligible for installation, but they aren't. This patch fixes that.
This is the result in the UI:
Related: https://issues.redhat.com/browse/MGMT-8329
=> MGMT-8329: Disks with mounted parititions are ineligible

src/commands/actions/next_step_runner.go
[MGMT-13420](https://issues.redhat.com//browse/MGMT-13420): Adding cleanup of next-step-runner before starting it.
In 4.12 for unknown reason podman fails to cleanup next-step-runner on agent restart and --rm doesn't help. To workaround the problem we are adding cleanup before starting it.
=> MGMT-13420: Adding cleanup of next-step-runner before starting it.

src/config/logs_sender_config.go, src/logs_sender/send_logs.go, src/logs_sender/send_logs_test.go
Currently our default for journal logs is 5 hours though we need to bring full journal logs as sometimes relevant issue is coming day before
=> MGMT-13665: Bring full journal by default in log gather

Dockerfile.ocp
This is a cherry-pick of https://github.com/openshift/assisted-installer-agent/pull/497
=> [release-4.12] OCPBUGS-7889: Add sg3_utils package

go.mod, go.sum, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/app.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/checks/engine.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/check_page.go, vendor/modules.txt
Bumping version to v0.0.0-20230227172155-0e307b16d36b
=> vendor agent-installer-utils

go.mod, go.sum, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/app.go, vendor/modules.txt
Bumping up the agent-installer-utils version
=> vendor agent-installer-utils to v0.0.0-20230228190135-5b30a39dadf6

go.mod, go.sum, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/app.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/checks/engine.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/check_page.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/controller.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/ui.go, vendor/modules.txt
Update agent-utils to v0.0.0-20230301211343-99aefff106c7
=> AGENT-565: revendor agent-utils

go.mod, go.sum, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/check_page.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/controller.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/ui.go, vendor/modules.txt
This patch vendors agent-installer-utils to import https://github.com/openshift/agent-installer-utils/pull/15
=> OCPBUGS-8390: vendor agent-installer-utils to v0.0.0-20230307094740-57807526b660

go.mod, go.sum, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/check_page.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/ui.go, vendor/modules.txt
Importing fix https://github.com/openshift/agent-installer-utils/pull/16
=> OCPBUGS-8677: vendor agent-installer-utils to v0.0.0-20230308101916-306b7995977e

src/commands/actions/next_step_runner.go, src/commands/actions/next_step_runner_test.go, src/ntp_synchronizer/mock_NtpSynchronizerDependencies.go, src/ntp_synchronizer/ntp_synchronizer.go, src/ntp_synchronizer/ntp_synchronizer_test.go
Running chronyc on host and not in container
=> MGMT-14319, OCPBUGS-11954: Fix chronyc segfault

src/inventory/disks.go, src/inventory/disks_test.go
Devices that have the "hidden" attribute should not be returned.  They actually have no corresponding block device file under /dev.  This property is set for the underlying components of multipath devices (usually NVMe).
=> [release-4.13] OCPBUGS-14992: Filter out hidden devices

go.mod, go.sum, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/app.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/checks/engine.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/controller.go, vendor/github.com/openshift/agent-installer-utils/tools/agent_tui/ui/ui.go, vendor/modules.txt
This patch fixes [OCPBUGS-15557](https://issues.redhat.com/browse/OCPBUGS-15557)
=> [release-4.13] OCPBUGS-15557: vendor agent-installer-utils to 79b142

src/inventory/disks.go, src/inventory/disks_test.go
In order to support the multipath device that is used by appliance nodes, return a disk with fake details when such device is detected. We can detect an appliance virtual device by the "agent" prefix on '/sys/block/dm-0/dm/name'.
The returned disk contains some fake values in order to avoid any validations and force installation on that disk.
This change is required for adding support in the appliance, see: https://github.com/openshift/appliance/pull/123
=> MGMT-15359: support appliance multipath virtual device

src/inventory/disks.go, src/inventory/disks_test.go
Devices that have the "hidden" attribute should not be returned.  They actually have no corresponding block device file under /dev.  This property is set for the underlying components of multipath devices (usually NVMe).
=> [release-ocm-2.8] OCPBUGS-14848: Filter out hidden devices (#558)

Dockerfile.assisted_installer_agent, Dockerfile.assisted_installer_agent-build, go.mod, src/apivip_check/apivip_check_test.go
=> MGMT-16039: upgrade to golang 1.20

go.mod, src/commands/commands_suite_test.go, src/commands/step_processor.go, src/commands/step_processor_test.go, src/session/inventory_session.go, src/session/inventory_session_test.go
Backporting 5 prs,
https://github.com/openshift/assisted-installer-agent/pull/442
https://github.com/openshift/assisted-installer-agent/pull/462
https://github.com/openshift/assisted-installer-agent/pull/459
https://github.com/openshift/assisted-installer-agent/pull/438
https://github.com/openshift/assisted-installer-agent/pull/583
=> OCPBUGS-23537: backport of agent retries

src/inventory/system_vendor.go, src/inventory/system_vendor_test.go
On LPAR there is a glitch preventing systemd-detect-virt to detect if there is a virtualized system or not. Even if the command returns correct results if executed via command line directly, it might happen that executing during agent run returns an error (-1). This is not a problem because for s390x architecture zVM and LPAR are not virtualized but only KVM.
With this fix LPAR will be set as Product to make LPAR more visible and add new test case.
List all the issues related to this PR
[ ] New Feature
Enhancement
[x ] Bug fix
Tests
Documentation
CI/CD
How was this code tested?
assited-installer-agent unit-tests
[x ] Reviewer's test appreciated
Waiting for CI to do a full test run
[x ] Manual (Elaborate on how it was tested)
Unit testing using 
skipper make unit-test TEST=./src/inventory …
=> MULTIARCH-4089: Fix LPAR handling

.tekton/assisted-installer-agent-mce-25-pull-request.yaml, .tekton/assisted-installer-agent-mce-25-push.yaml
renaming dockerfile for konflux pipelines
=> NO-ISSUE: rename dockerfile

src/commands/actions/install_cmd.go
https://issues.redhat.com/browse/OCPBUGS-31423
Split the install command into two parts: pulling the installer image then running the install command. Pulling separately and ahead of time prevents possible flakes when pulling the image. Mostly relevant for day 2 hosts since we don't run the container image availability command before installing.
/cc @tsorya
=> OCPBUGS-31423: Try to pull installer image before installing

src/commands/actions/download_boot_artifacts_cmd.go
Adds a retry when downloading the boot artifacts from assisted service in case there are connection issues or a server disruption.
/cc @carbonin
=> MGMT-18839: Retry downloading boot artifacts

Dockerfile.assisted_installer_agent
This PR adds a required dependency for the inventory executable in the container image.
=> MGMT-18923: Add hwdata package to inventory dependencies

src/inventory/gpu_test.go
There is no real change to user code in this PR. Just an additional test was added to make sure that in the future no one groups GPUs under the same PCI address (that would be a breaking change)
=> NO-ISSUE: Add additional test for GPU cards with multiple PCI functions

Dockerfile.assisted_installer_agent-build
Same as https://github.com/openshift/assisted-service/pull/6902
=> NO-ISSUE: Pin gocov version

.tekton/assisted-installer-agent-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-installer-agent-mce-downstream-2-13-push.yaml
This will finish the onboarding process for acm 2.13
Part-of [MGMT-19408](https://issues.redhat.com//browse/MGMT-19408)
=> MGMT-19408: Create tekton pipelines for acm 2.13

Dockerfile.assisted_installer_agent-downstream
Add downstream dockerfile to upstream repo for konflux migration from cpaas.
Part-of [MGMT-19453](https://issues.redhat.com//browse/MGMT-19453)
=> MGMT-19453: Add downstream dockerfile

.tekton/assisted-installer-agent-downstream-main-pull-request.yaml, .tekton/assisted-installer-agent-downstream-main-push.yaml, .tekton/assisted-installer-agent-mce-downstream-2-13-pull-request.yaml, .tekton/assisted-installer-agent-mce-downstream-2-13-push.yaml, .tekton/assisted-installer-agent-mce-downstream-main-pull-request.yaml, .tekton/assisted-installer-agent-mce-downstream-main-push.yaml, Dockerfile.assisted_installer_agent-downstream, Dockerfile.assisted_installer_agent-mce, rpm-prefetching/README.md, rpm-prefetching/rpms.in.yaml, rpm-prefetching/rpms.lock.yaml
Configure the following things for releasing in konflux:
- Hermetic builds
- Pushing source image.
- Adding label io.openshift.tags.
- Setting up snyk
Part-of [MGMT-19645](https://issues.redhat.com//browse/MGMT-19645)
=> MGMT-19645: Configure a few things for releasing in konflux

renovate.json
Add renovate config to limiot number of konflux PR
With that config, PR should be automerged when tests succeeded
=> MGMT-19734: Add renovate config to limit number of PRs

.tekton/assisted-installer-agent-acm-ds-2-13-pull-request.yaml, .tekton/assisted-installer-agent-acm-ds-2-13-push.yaml
Tasks will become mandatory the 1st of April
=> MGMT-20149: Add required sast tasks for Konflux

go.mod, go.sum, vendor/github.com/jaypipes/ghw/Dockerfile, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/alias.go, vendor/github.com/jaypipes/ghw/host.go, vendor/github.com/jaypipes/ghw/pkg/accelerator/accelerator.go, vendor/github.com/jaypipes/ghw/pkg/accelerator/accelerator_linux.go, vendor/github.com/jaypipes/ghw/pkg/accelerator/accelerator_stub.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_darwin.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_darwin.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/address/address.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_linux.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/pack.go, vendor/github.com/jaypipes/ghw/pkg/topology/topology.go, vendor/github.com/jaypipes/ghw/pkg/topology/topology_linux.go, vendor/github.com/jaypipes/ghw/pkg/topology/topology_windows.go, vendor/modules.txt
Update to latest ghw version `v0.16.0`
=> OCPBUGS-52994: Update to latest ghw version

go.mod, go.sum, vendor/github.com/jaypipes/ghw/Dockerfile, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/alias.go, vendor/github.com/jaypipes/ghw/host.go, vendor/github.com/jaypipes/ghw/pkg/accelerator/accelerator.go, vendor/github.com/jaypipes/ghw/pkg/accelerator/accelerator_linux.go, vendor/github.com/jaypipes/ghw/pkg/accelerator/accelerator_stub.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_darwin.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_darwin.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/address/address.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_linux.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/pack.go, vendor/github.com/jaypipes/ghw/pkg/topology/topology.go, vendor/github.com/jaypipes/ghw/pkg/topology/topology_linux.go, vendor/github.com/jaypipes/ghw/pkg/topology/topology_windows.go, vendor/modules.txt
This is a manual cherry-pick of https://github.com/openshift/assisted-installer-agent/pull/986
=> [release-4.16] OCPBUGS-55443: Update to latest ghw version

OWNERS_ALIASES
=> [release-ocm-2.14] NO-ISSUE: Reduce owners list for release-2.14 branch

.tekton/assisted-installer-agent-acm-ds-2-15-pull-request.yaml, .tekton/assisted-installer-agent-acm-ds-2-15-push.yaml
=> NO-ISSUE: Modify Konflux YAMLs to ocm-2.15

src/connectivity_check/mtu_checker_test.go
=> NO-ISSUE: Test

src/connectivity_check/mtu_checker_test.go
Reverts openshift/assisted-installer-agent#1015
=> Revert "NO-ISSUE: Test"

src/config/logs_sender_config.go
https://issues.redhat.com/browse/MGMT-20141
=> MGMT-20141: collecting and uploading ironic-agent logs

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/modules.txt
=> OCPBUGS-58845,OCPBUGS-58844: Bump glog to v1.2.5 in release-4.19

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/modules.txt
=> OCPBUGS-58660,OCPBUGS-58655: Bump glog to v1.2.5 in release-4.18

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_linux.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_other.go, vendor/github.com/golang/glog/glog_file_posix.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/github.com/golang/glog/glog_flags.go, vendor/github.com/golang/glog/internal/logsink/logsink.go, vendor/github.com/golang/glog/internal/logsink/logsink_fatal.go, vendor/github.com/golang/glog/internal/stackdump/stackdump.go, vendor/modules.txt
=> OCPBUGS-58868,OCPBUGS-58867: Bump glog to v1.2.5 in release-4.12
